### ISSUE TITLE
Feature Tools throwing KeyError while doing DFS  

### ISSUE THREAD

**Issue by engineeryashsaxena** [FeatureLabs/featuretools#663] opened 2019-07-11 21:06 UTC
I am getting the following error while performing DFS : 

`feature_matrix, feature_names = ft.dfs(entityset = es, target_entity = 'customer', agg_primitives=agg_primitives, trans_primitives=trans_primitives)`

The error I am getting is : 

`KeyError: 3.0`

Description of entire error statement is : 

```
KeyError: 3.0                               
Traceback (most recent call last)
<command-510505> in <module>()
     
     35 feature_matrix, feature_names = ft.dfs(entityset = es, target_entity = 'customer', agg_primitives=agg_primitives, trans_primitives=trans_primitives,)
 
/databricks/python/lib/python3.5/site-packages/featuretools/utils/entry_point.py in function_wrapper(*args, **kwargs)
     44                     ep.on_error(error=e,
     45                                 runtime=runtime)
---> 46                 raise e
     47 
     48             # send return value

/databricks/python/lib/python3.5/site-packages/featuretools/utils/entry_point.py in function_wrapper(*args, **kwargs)
     36                 # call function
     37                 start = time.time()
---> 38                 return_value = func(*args, **kwargs)
     39                 runtime = time.time() - start
     40             except Exception as e:

/databricks/python/lib/python3.5/site-packages/featuretools/synthesis/dfs.py in dfs(entities, relationships, entityset, target_entity, cutoff_time, instance_ids, agg_primitives, trans_primitives, groupby_trans_primitives, allowed_paths, max_depth, ignore_entities, ignore_variables, seed_features, drop_contains, drop_exact, where_primitives, max_features, cutoff_time_in_index, save_progress, features_only, training_window, approximate, chunk_size, n_jobs, dask_kwargs, verbose, return_variable_types)
    213                                                   n_jobs=n_jobs,
    214                                                   dask_kwargs=dask_kwargs,
--> 215                                                   verbose=verbose)
    216     else:
    217         feature_matrix = calculate_feature_matrix(features,

/databricks/python/lib/python3.5/site-packages/featuretools/computational_backends/calculate_feature_matrix.py in calculate_feature_matrix(features, entityset, cutoff_time, instance_ids, entities, relationships, cutoff_time_in_index, training_window, approximate, save_progress, verbose, chunk_size, n_jobs, dask_kwargs)
    265                                                  cutoff_df_time_var=cutoff_df_time_var,
    266                                                  target_time=target_time,
--> 267                                                  pass_columns=pass_columns)
    268 
    269     feature_matrix = pd.concat(feature_matrix)

/databricks/python/lib/python3.5/site-packages/featuretools/computational_backends/calculate_feature_matrix.py in linear_calculate_chunks(chunks, feature_set, approximate, training_window, verbose, save_progress, entityset, no_unapproximated_aggs, cutoff_df_time_var, target_time, pass_columns)
    496                                           no_unapproximated_aggs,
    497                                           cutoff_df_time_var,
--> 498                                           target_time, pass_columns)
    499         feature_matrix.append(_feature_matrix)
    500         # Do a manual garbage collection in case objects from calculate_chunk

/databricks/python/lib/python3.5/site-packages/featuretools/computational_backends/calculate_feature_matrix.py in calculate_chunk(chunk, feature_set, entityset, approximate, training_window, verbose, save_progress, no_unapproximated_aggs, cutoff_df_time_var, target_time, pass_columns)
    341                                            ids,
    342                                            precalculated_features=precalculated_features_trie,
--> 343                                            training_window=window)
    344 
    345             id_name = _feature_matrix.index.name

/databricks/python/lib/python3.5/site-packages/featuretools/computational_backends/utils.py in wrapped(*args, **kwargs)
     35         def wrapped(*args, **kwargs):
     36             if save_progress is None:
---> 37                 r = method(*args, **kwargs)
     38             else:
     39                 time = args[0].to_pydatetime()

/databricks/python/lib/python3.5/site-packages/featuretools/computational_backends/calculate_feature_matrix.py in calc_results(time_last, ids, precalculated_features, training_window)
    316                                               ignored=all_approx_feature_set)
    317 
--> 318             matrix = calculator.run(ids)
    319             return matrix
    320 

/databricks/python/lib/python3.5/site-packages/featuretools/computational_backends/feature_set_calculator.py in run(self, instance_ids)
    129         for feat in self.feature_set.target_features:
    130             column_list.extend(feat.get_feature_names())
--> 131         return df[column_list]
    132 
    133     def _calculate_features_for_entity(self, entity_id, feature_trie, df_trie,

/databricks/python/lib/python3.5/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2932                 key = list(key)
   2933             indexer = self.loc._convert_to_indexer(key, axis=1,
-> 2934                                                    raise_missing=True)
   2935 
   2936         # take() does not accept boolean indexers

/databricks/python/lib/python3.5/site-packages/pandas/core/indexing.py in _convert_to_indexer(self, obj, axis, is_setter, raise_missing)
   1352                 kwargs = {'raise_missing': True if is_setter else
   1353                           raise_missing}
-> 1354                 return self._get_listlike_indexer(obj, axis, **kwargs)[1]
   1355         else:
   1356             try:

/databricks/python/lib/python3.5/site-packages/pandas/core/indexing.py in _get_listlike_indexer(self, key, axis, raise_missing)
   1159         self._validate_read_indexer(keyarr, indexer,
   1160                                     o._get_axis_number(axis),
-> 1161                                     raise_missing=raise_missing)
   1162         return keyarr, indexer
   1163 

/databricks/python/lib/python3.5/site-packages/pandas/core/indexing.py in _validate_read_indexer(self, key, indexer, axis, raise_missing)
   1250             if not(self.name == 'loc' and not raise_missing):
   1251                 not_found = list(set(key) - set(ax))
-> 1252                 raise KeyError("{} not in index".format(not_found))
   1253 
   1254             # we skip the warning on Categorical/Interval

KeyError: 3.0
```

**Comment by engineeryashsaxena** [comment] 2019-07-11 21:09
The agg and trans primitives I am using are : 
```
agg_primitives=[
        'std', 'min', 'max', 'mean', 
        'percent_true', 'last', 'count', 
        'trend', 'n_most_common', 'time_since_last',        
        'avg_time_between'
]
trans_primitives=[
        'year', 'month', 'weekday', 'percentile', 
        'isin', 'cum_mean', 'time_since_previous'
]

```

Also I made verbose=True in dfs function and I am getting this after the following performance : 

```
Built 913 features

Elapsed: 00:00 | Remaining: ? | Progress:   0%|          | Calculated: 0/11 chunks
Elapsed: 02:28 | Remaining: 24:48 | Progress:   9%|▉         | Calculated: 1/11 chunks
Elapsed: 05:49 | Remaining: 24:38 | Progress:  18%|█▊        | Calculated: 2/11 chunks
Elapsed: 12:55 | Remaining: 32:24 | Progress:  27%|██▋       | Calculated: 3/11 chunks
Elapsed: 16:58 | Remaining: 28:19 | Progress:  36%|███▋      | Calculated: 4/11 chunks
Elapsed: 22:06 | Remaining: 26:15 | Progress:  45%|████▌     | Calculated: 5/11 chunks
Elapsed: 27:11 | Remaining: 22:56 | Progress:  55%|█████▍    | Calculated: 6/11 chunks
Elapsed: 36:27 | Remaining: 23:57 | Progress:  64%|██████▎   | Calculated: 7/11 chunks
Elapsed: 51:34 | Remaining: 26:11 | Progress:  73%|███████▎  | Calculated: 8/11 chunks

```

**Comment by engineeryashsaxena** [comment] 2019-07-11 21:13
When I drop certain columns from one of the entity in the entity set , I am not getting this error but I can't afford to drop the column as I need to create features around that , so I am stuck here 

Also , when I provide a cutoff dataset then I see this KeyError also : 

 `
KeyError: "['N_MOST_COMMON(segment.WEEKDAY(Segment_date))__1', 'N_MOST_COMMON(segment.MONTH(Segment_date))__1', 'N_MOST_COMMON(segment.YEAR(Segment_date))__2', 'N_MOST_COMMON(segment.YEAR(Segment_date))__0', 'N_MOST_COMMON(segment.MONTH(Segment_date))__0', 'N_MOST_COMMON(segment.MONTH(Segment_date))__2', 'N_MOST_COMMON(segment.YEAR(Segment_date))__1', 'N_MOST_COMMON(segment.value_segment_detail)__1', 'N_MOST_COMMON(segment.value_segment_detail)__2', 'N_MOST_COMMON(segment.value_segment_detail)__0', 'N_MOST_COMMON(segment.WEEKDAY(Segment_date))__0', 'N_MOST_COMMON(segment.WEEKDAY(Segment_date))__2'] not in index"
`

**Comment by engineeryashsaxena** [comment] 2019-07-11 21:32
@kmax12 If you can help here please

**Comment by kmax12** [comment] 2019-07-12 16:40
@engineeryashsaxena are you able to provide a minimally reproducible example we can run to replicate this error?

**Comment by engineeryashsaxena** [comment] 2019-07-22 14:46
I would have if I could have but I am not able to share the data . I dig deeper and found that the problem was occurring because of an aggregate primitive "n_most_common" . When I removed that it seems to work fine.I understand this is not the most optimal way but we had to find a fix to move forward and we can afford to loose that primitive so we took that .
Thanks for you quick reply.

**Comment by engineeryashsaxena** [comment] 2019-07-22 14:50
If you can share your experience around this then it will be really helpful :  

I have multiple datasets which are very large and I want to apply deep feature synthesis to generate feature matrix for them , I am using PySpark so I have divided the data into different partitions and then I am trying to create feature matrix for each partition , the problem comes when I have to do One Hot Encoding on the categorical features generated from the feature matrix . I am not able to get consistency in the features which are created from different partitions so I am unable to merge them for training the model . Can you please suggest the optimal and correct way to do this ?

**Comment by PengchongLiu** [comment] 2019-09-06 00:05
I have a similar issue using version 0.10.1

> KeyError: 'Entity 0 does not exist in transactions'

`es = ft.demo.load_mock_customer(return_entityset=True)
feature_matrix, feature_defs = ft.dfs(entities=es,
                                      target_entity='customers',
                                      max_depth=2,
                                      agg_primitives=["mean", "max", "min", "std", "skew","percent_true"],
                                      trans_primitives=["time_since_previous", "cum_max", "cum_mean"],
                                      verbose=True
                                     )`

**Comment by kmax12** [comment] 2020-05-21 16:57
closing since we don't have a reproducible example and the stack traces shows python 3.5, which is no longer supported. feel free to reopen if this is still and issue and you're able to share more info.

**Closed by kmax12** 2020-05-21 16:57 UTC

**Comment by imadcat** [comment] 2022-04-02 16:33
> If you can share your experience around this then it will be really helpful :
> 
> I have multiple datasets which are very large and I want to apply deep feature synthesis to generate feature matrix for them , I am using PySpark so I have divided the data into different partitions and then I am trying to create feature matrix for each partition , the problem comes when I have to do One Hot Encoding on the categorical features generated from the feature matrix . I am not able to get consistency in the features which are created from different partitions so I am unable to merge them for training the model . Can you please suggest the optimal and correct way to do this ?

I got the same error when I was generating a feature matrix from the testing data with the feature_defs synthesized on the training data, testing data has some one-hot columns that do not exist in the training data. Before I figure out how to leverage the new one-hot columns, is there a way to ignore those new columns when doing featuretools.calculate_feature_matrix?
`featuretools.calculate_feature_matrix(feature_defs, entityset_test)`

**Comment by thehomebrewnerd** [comment] 2022-04-04 14:23
@imadcat I'm not entirely sure I understand the problem you are encountering. Are you able to provide a reproducible example to illustrate your problem?

If the test data that you input to DFS contains additional columns that were not present in your original training data, these columns should ignored when calling `calculate_feature_matrix`. Featuretools should only use the columns that were used to create the original feature defs from the training data, and ignore any additional columns in the test dataframe when calculating the test feature matrix.

On the other hand, if your training data contains columns that are not present in your test data, this could be problematic when you call `calculate_feature_matrix`. If you know your training data has columns that are not present in your test data, you can ignore these columns in the original `ft.dfs` call by using the `ignore_columns` parameter documented here: https://featuretools.alteryx.com/en/stable/guides/specifying_primitive_options.html#Specifying-Options-for-an-Entire-Run

If this information doesn't help you resolve your problem, please provide more detail to help us troubleshoot further.
