### ISSUE TITLE
cum_count returns incorrect values when used as trans_primitives

### ISSUE THREAD

**Issue by bigheadming** [FeatureLabs/featuretools#686] opened 2019-07-28 20:45 UTC
#### Bug/Feature Request Title
cum_count returns incorrect values when used as trans_primitives

#### Bug/Feature Request Description
```
import featuretools as ft
es = ft.demo.load_mock_customer(return_entityset=True)
print(ft.__version__)
```
###### 0.9.1

`print(ft.show_info())`
###### None

```
from pprint import pprint

import sys
print(sys.version)
```
###### 3.6.8 |Anaconda custom (64-bit)|

```
fm, features = ft.dfs(
  entityset = es,
  target_entity = "customers",
  agg_primitives = ["sum"],
  trans_primitives = ["month", "cum_count"],
  max_depth=2,
  #instance_ids = [4],
)
pprint(features)
```
######  <Feature: SUM(sessions.CUM_COUNT(customer_id))>]

`fm.reset_index(inplace=True)`
`print(fm.query("customer_id == 4").T)`
##### (1) Get the list of session_id by customer_id == 4
```
session_id_customer_4 = es["sessions"].df.query("customer_id == 4")["session_id"].to_list()
print(session_id_customer_4)
```
##### (3) To verify the above, let calculate the session_id list for each customer_id
```
session_ids_customer = dict()
for _c in es["customers"].df["customer_id"].to_list():
  session_ids_customer[_c] = es["sessions"].df.query("customer_id == @_c")["session_id"].to_list()

for _c in sorted(session_ids_customer.keys()):
  print("customer_id = ", _c, ", session_ids = ", session_ids_customer[_c], ", sum of list = ", sum(session_ids_customer[_c]))
```
customer_id =  1 , session_ids =  [4, 6, 9, 14, 18, 26, 27, 29] , sum of list =  133
customer_id =  2 , session_ids =  [1, 10, 15, 16, 17, 31, 33] , sum of list =  123
customer_id =  3 , session_ids =  [7, 19, 23, 25, 34, 35] , sum of list =  143
customer_id =  4 , session_ids =  [3, 5, 8, 11, 12, 13, 21, 22] , sum of list =  95
customer_id =  5 , session_ids =  [2, 20, 24, 28, 30, 32] , sum of list =  136
        

##### (4) Check the value of SUM(sessions.CUM_COUNT(customer_id)) for each customer_id
`print(fm[["customer_id", "SUM(sessions.CUM_COUNT(customer_id))"]])`
##### (5) Expected result from SUM(sessions.CUM_COUNT(customer_id))
```
def cum_count_x(_list):
  from featuretools.primitives import CumCount as cc
  _cumcount = cc()
  _result = _cumcount(_list).sum()
  return _result

for _c in sorted(session_ids_customer.keys()):
  print("customer_id = ", _c, ", session_ids = ", session_ids_customer[_c], ", cum_count of list = ", cum_count_x(session_ids_customer[_c]))
```

**Comment by rwedge** [comment] 2020-05-14 15:21
Sorry for the late reply @bigheadming , the issue is that if you want `CumCount` to filter by an id column (like customer id) it should be added to the `groupby_trans_primitives` list instead of `trans_primitives`, like this:

```python
fm, features = ft.dfs(
  entityset = es,
  target_entity = "customers",
  agg_primitives = ["sum"],
  trans_primitives = ["month"],
  groupby_trans_primitives = ["cum_count"],
  max_depth=2,
  #instance_ids = [4],
)
```

This will create a different feature, `SUM(sessions.CUM_COUNT(customer_id) by customer_id)`, that has the values you were expecting:

```
>>> useful_cols = ["customer_id", "SUM(sessions.CUM_COUNT(customer_id) by customer_id)"]
>>> print(fm[useful_cols])
   customer_id  SUM(sessions.CUM_COUNT(customer_id) by customer_id)
0            5                                               21.0  
1            4                                               36.0  
2            1                                               36.0  
3            3                                               21.0  
4            2                                               28.0  
```

Closing this issue but feel free to re-open if you have additional questions or would like more clarification!

**Closed by rwedge** 2020-05-14 15:21 UTC
