### ISSUE TITLE
DFS does not always return the same feature matrix when using max_features parameter

### ISSUE THREAD

**Issue by thehomebrewnerd** [FeatureLabs/featuretools#833] opened 2019-12-03 20:02 UTC
#### Bug Description

The current implementation of DFS does not always return the exact same feature matrix when using the `max_features` parameter. This is illustrated in the attached notebook.

In order to duplicate this behavior, you must completely restart the notebook kernel as specified in the notebook. If you run DFS twice back to back without restarting the kernel you will get the same feature matrix each time, but restarting the kernel results in a different set of features.

#### Expected Output
The expected behavior is that running DFS with the same parameters will return the same set of features each time.

[max_features_not_deterministic.ipynb.zip](https://github.com/FeatureLabs/featuretools/files/3918462/max_features_not_deterministic.ipynb.zip)

**Comment by systemshift** [comment] 2019-12-04 05:47
The issue is reproducible without using `max_features` parameter as well

**Comment by thehomebrewnerd** [comment] 2019-12-04 14:00
> The issue is reproducible without using `max_features` parameter as well

Just to add a little to this...

I have not tested this extensively, but during earlier testing (outside of this notebook), I observed that if I set `max_features=-1` to not restrict the number of features generated, the features returned were the same, but the column ordering is different in the feature matrix dataframes so they aren't strictly equal. 

When the number of features was restricted, the specific features returned varied, both in order and in terms of the features that were returned.

**Comment by thehomebrewnerd** [comment] 2020-07-20 13:39
Additional testing has revealed that this behavior happens even with `max_features=-1` on the ecommerce entityset generated by `ft..tests.testing_utils.make_ecommerce_entityset`. In that case, the total number of features returned changes after a kernel restart.

**Comment by tamargrey** [comment] 2020-07-27 23:12
> Additional testing has revealed that this behavior happens even with `max_features=-1` on the ecommerce entityset generated by `ft.tests.testing_utils.make_ecommerce_entityset`. In that case, the total number of features returned changes after a kernel restart.

Seems like this is a separate issue having to do with having different orderings of of `trans_primitives`  #1087

**Comment by rwedge** [comment] 2020-09-16 18:47
@tamargrey is this issue resolved now that #1088 and #1119 are in?

**Comment by tamargrey** [comment] 2020-09-16 20:44
> @tamargrey is this issue resolved now that #1088 and #1119 are in?

Yes--closing

**Closed by tamargrey** 2020-09-16 20:44 UTC
